with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"

packages:
  github.com/kuromii5/notification-service/internal/service/notification:
    interfaces:
      UserPrefsRepo:
      ProfileRepo:
      EmailSender:
      IdempotencyRepo:
