// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIdempotencyRepo is an autogenerated mock type for the IdempotencyRepo type
type MockIdempotencyRepo struct {
	mock.Mock
}

type MockIdempotencyRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyRepo) EXPECT() *MockIdempotencyRepo_Expecter {
	return &MockIdempotencyRepo_Expecter{mock: &_m.Mock}
}

// IsProcessed provides a mock function with given fields: ctx, eventID
func (_m *MockIdempotencyRepo) IsProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdempotencyRepo_IsProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProcessed'
type MockIdempotencyRepo_IsProcessed_Call struct {
	*mock.Call
}

// IsProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *MockIdempotencyRepo_Expecter) IsProcessed(ctx interface{}, eventID interface{}) *MockIdempotencyRepo_IsProcessed_Call {
	return &MockIdempotencyRepo_IsProcessed_Call{Call: _e.mock.On("IsProcessed", ctx, eventID)}
}

func (_c *MockIdempotencyRepo_IsProcessed_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *MockIdempotencyRepo_IsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIdempotencyRepo_IsProcessed_Call) Return(_a0 bool, _a1 error) *MockIdempotencyRepo_IsProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdempotencyRepo_IsProcessed_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockIdempotencyRepo_IsProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function with given fields: ctx, eventID
func (_m *MockIdempotencyRepo) MarkProcessed(ctx context.Context, eventID uuid.UUID) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdempotencyRepo_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type MockIdempotencyRepo_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *MockIdempotencyRepo_Expecter) MarkProcessed(ctx interface{}, eventID interface{}) *MockIdempotencyRepo_MarkProcessed_Call {
	return &MockIdempotencyRepo_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, eventID)}
}

func (_c *MockIdempotencyRepo_MarkProcessed_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *MockIdempotencyRepo_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIdempotencyRepo_MarkProcessed_Call) Return(_a0 error) *MockIdempotencyRepo_MarkProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdempotencyRepo_MarkProcessed_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIdempotencyRepo_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdempotencyRepo creates a new instance of MockIdempotencyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyRepo {
	mock := &MockIdempotencyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
