// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProfileRepo is an autogenerated mock type for the ProfileRepo type
type MockProfileRepo struct {
	mock.Mock
}

type MockProfileRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepo) EXPECT() *MockProfileRepo_Expecter {
	return &MockProfileRepo_Expecter{mock: &_m.Mock}
}

// GetUsername provides a mock function with given fields: ctx, userID
func (_m *MockProfileRepo) GetUsername(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsername")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileRepo_GetUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsername'
type MockProfileRepo_GetUsername_Call struct {
	*mock.Call
}

// GetUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProfileRepo_Expecter) GetUsername(ctx interface{}, userID interface{}) *MockProfileRepo_GetUsername_Call {
	return &MockProfileRepo_GetUsername_Call{Call: _e.mock.On("GetUsername", ctx, userID)}
}

func (_c *MockProfileRepo_GetUsername_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProfileRepo_GetUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProfileRepo_GetUsername_Call) Return(_a0 string, _a1 error) *MockProfileRepo_GetUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileRepo_GetUsername_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *MockProfileRepo_GetUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileRepo creates a new instance of MockProfileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepo {
	mock := &MockProfileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
