// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/notification-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserPrefsRepo is an autogenerated mock type for the UserPrefsRepo type
type MockUserPrefsRepo struct {
	mock.Mock
}

type MockUserPrefsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPrefsRepo) EXPECT() *MockUserPrefsRepo_Expecter {
	return &MockUserPrefsRepo_Expecter{mock: &_m.Mock}
}

// GetPreferences provides a mock function with given fields: ctx, userID
func (_m *MockUserPrefsRepo) GetPreferences(ctx context.Context, userID uuid.UUID) (*domain.UserPreferences, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *domain.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.UserPreferences, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.UserPreferences); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPrefsRepo_GetPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreferences'
type MockUserPrefsRepo_GetPreferences_Call struct {
	*mock.Call
}

// GetPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserPrefsRepo_Expecter) GetPreferences(ctx interface{}, userID interface{}) *MockUserPrefsRepo_GetPreferences_Call {
	return &MockUserPrefsRepo_GetPreferences_Call{Call: _e.mock.On("GetPreferences", ctx, userID)}
}

func (_c *MockUserPrefsRepo_GetPreferences_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserPrefsRepo_GetPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserPrefsRepo_GetPreferences_Call) Return(_a0 *domain.UserPreferences, _a1 error) *MockUserPrefsRepo_GetPreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPrefsRepo_GetPreferences_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.UserPreferences, error)) *MockUserPrefsRepo_GetPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserPrefsRepo creates a new instance of MockUserPrefsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPrefsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPrefsRepo {
	mock := &MockUserPrefsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
