name: Notification Service CI

on:
  push:
    branches: ["main", "dev"]
    tags: ['v[0-9]*.[0-9]*']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.10.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -o bin/notification-service ./cmd

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Clone migrations
        run: git clone https://github.com/kuromii5/chat-bot-migrations.git ../migrations

      - name: Run integration tests
        run: go test ./tests/integration/ -tags=integration -v -count=1

  build-and-push:
    needs: [lint, test, integration-test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
